# Generated by Django 5.2.7 on 2026-01-09 09:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('type_client', models.CharField(default='particulier', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ferme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_poulet', models.CharField(default='broiler', max_length=50)),
                ('poids_cible', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('duree_cycle', models.PositiveIntegerField(default=42)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('en_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Article sans nom', max_length=100)),
                ('type_aliment', models.CharField(choices=[('demarrage', 'Démarrage'), ('croissance', 'Croissance'), ('finition', 'Finition'), ('pre_finition', 'Pré-finition'), ('medicament', 'Médicament'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unite', models.CharField(choices=[('kg', 'kg'), ('sac', 'sac'), ('litre', 'litre')], default='kg', max_length=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Veterinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('employe', 'Employé'), ('client', 'Client')], default='employe', max_length=20, verbose_name='Rôle')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(default='employe', max_length=50)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='poulets_app.ferme')),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite_max', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)])),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='poulets_app.ferme')),
            ],
        ),
        migrations.CreateModel(
            name='Bande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField()),
                ('nb_poulets_init', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(choices=[('croissance', 'En Croissance'), ('prete', 'Prête'), ('vendue', 'Vendue')], default='croissance', max_length=20)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.batiment')),
                ('employe_responsable', models.ManyToManyField(blank=True, related_name='bandes', to='poulets_app.employe')),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.gamme')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('provende', 'Provende'), ('medicament', 'Médicament')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_expiry', models.DateField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='poulets_app.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantite_achetee', models.PositiveIntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.fournisseur')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantite_vendue', models.PositiveIntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='poulets_app.bande')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Mortalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nombre', models.PositiveIntegerField()),
                ('cause', models.CharField(choices=[('maladie', 'Maladie'), ('chaleur', 'Chaleur'), ('froid', 'Froid'), ('asphyxie', 'Asphyxie'), ('ecrasement', 'Écrasement'), ('cannibalisme', 'Cannibalisme'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('bande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalite_set', to='poulets_app.bande')),
            ],
            options={
                'unique_together': {('bande', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Pesee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poids_moyen', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('nombre_poulets_peses', models.PositiveIntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('bande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesee_set', to='poulets_app.bande')),
            ],
            options={
                'unique_together': {('bande', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_aliment', models.CharField(max_length=50)),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('bande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentation_set', to='poulets_app.bande')),
                ('stock_provenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentations', to='poulets_app.stock')),
            ],
            options={
                'unique_together': {('bande', 'date', 'type_aliment')},
            },
        ),
    ]
