# Generated by Django 5.2.7 on 2025-10-28 01:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite_max', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('type_client', models.CharField(default='particulier', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(default='employe', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ferme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_poulet', models.CharField(default='broiler', max_length=50)),
                ('poids_cible', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('duree_cycle', models.PositiveIntegerField(default=42)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField()),
                ('nb_poulets_init', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('statut', models.CharField(choices=[('croissance', 'En Croissance'), ('prete', 'Prête'), ('vendue', 'Vendue')], default='croissance', max_length=20)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.batiment')),
                ('employe_responsable', models.ManyToManyField(blank=True, related_name='bandes', to='poulets_app.employe')),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.gamme')),
            ],
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nb_deces', models.PositiveIntegerField(default=1)),
                ('cause', models.CharField(blank=True, max_length=200)),
                ('bande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deces', to='poulets_app.bande')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='ferme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='poulets_app.ferme'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='ferme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='poulets_app.ferme'),
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('provende', 'Provende'), ('medicament', 'Médicament')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_expiry', models.DateField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='poulets_app.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantite_achetee', models.PositiveIntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.fournisseur')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_dispo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_min', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='poulets_app.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantite_vendue', models.PositiveIntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='poulets_app.bande')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_admin', models.DateField(auto_now_add=True)),
                ('bande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='poulets_app.bande')),
                ('veterinaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poulets_app.veterinaire')),
            ],
        ),
    ]
