# Generated by Django 5.2.7 on 2026-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poulets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produitvente',
            options={'ordering': ['nom'], 'verbose_name': 'Produit en vente', 'verbose_name_plural': 'Produits en vente'},
        ),
    ]
